# Generated by Django 5.0.1 on 2026-05-24 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category_app", "0001_initial"),
        ("genre_app", "0002_alter_genremodel_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="CategoryModel",
        ),
    ]
