# Generated by Django 5.0.1 on 2026-05-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('genre_app', '0002_alter_genremodel_table'),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
