# Generated by Django 5.0.1 on 2026-05-24 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cast_member_app", "0001_initial"),
        ("category_app", "0002_rename_category_categorymodel"),
        ("genre_app", "0002_alter_genremodel_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageMediaModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checksum", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("raw_location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VideoMediaModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checksum", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("raw_location", models.CharField(max_length=255)),
                ("encoded_location", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                            ("ERROR", "ERROR"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("launch_year", models.IntegerField()),
                ("duration", models.DecimalField(decimal_places=2, max_digits=10)),
                ("published", models.BooleanField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("ER", "ER"),
                            ("L", "L"),
                            ("AGE_10", "AGE_10"),
                            ("AGE_12", "AGE_12"),
                            ("AGE_14", "AGE_14"),
                            ("AGE_16", "AGE_16"),
                            ("AGE_18", "AGE_18"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "banner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_banner",
                        to="video_app.imagemediamodel",
                    ),
                ),
                (
                    "cast_members",
                    models.ManyToManyField(
                        related_name="videos", to="cast_member_app.castmembermodel"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="videos", to="category_app.categorymodel"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="videos", to="genre_app.genremodel"
                    ),
                ),
                (
                    "thumbnail",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_thumbnail",
                        to="video_app.imagemediamodel",
                    ),
                ),
                (
                    "thumbnail_half",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_thumbnail_half",
                        to="video_app.imagemediamodel",
                    ),
                ),
                (
                    "trailer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_trailer",
                        to="video_app.videomediamodel",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_file",
                        to="video_app.videomediamodel",
                    ),
                ),
            ],
        ),
    ]
