# Generated by Django 5.0.1 on 2026-05-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genremodel',
            table='genre',
        ),
    ]
